src/Actividad/Controllers/SolicitadosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Actividad.Models;
using Actividad.Viewmodels;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Actividad.Controllers
{
    public class SolicitadosController : Controller
    {
        private readonly IUsuariosRepositorio _usuariosRepositorios;
        private readonly Solicitados _solicitados;

        public SolicitadosController(IUsuariosRepositorio usuariosRepositorios, Solicitados solicitados)
        {
            _usuariosRepositorios = usuariosRepositorios;
            _solicitados = solicitados;
        }

        public ViewResult Index()
        {
            var soliItems = _solicitados.GetSolicitadosItems();
            _solicitados.SolicitadosItems = soliItems;

            var solicitadosViewModel = new SolicitadosViewModel
            {
                Solicitados = _solicitados,
                SolicitadosTotal = _solicitados.GetSolicitadosTotal()
            };
            return View(solicitadosViewModel);
        }

        public RedirectToActionResult AgregarASolicitados (int codigoUsuario)
        {
            var usuarioSeleccionado = _usuariosRepositorios.Usuarios.FirstOrDefault(u => u.CodigoUsuario == codigoUsuario);
            if(usuarioSeleccionado != null)
            {
                _solicitados.AgregarItemSolicitado(usuarioSeleccionado, 1);
            }
            return RedirectToAction("Index");
        }
        public RedirectToActionResult EliminarDeSolicitados( int codigoUsuario)
        {
            var usuarioSeleccionado = _usuariosRepositorios.Usuarios.FirstOrDefault(u => u.CodigoUsuario == codigoUsuario);
            if (usuarioSeleccionado != null)
            {
                _solicitados.EliminarItemSolicitado(usuarioSeleccionado);
            }
            return RedirectToAction("Index");
        }
    }
}

src/Actividad/Views/Shared/DesplegarNiveles.cshtml
<div class="container">
    <div class="table-responsive">
        <style>
            #thead {
                border-bottom: solid 5px #0F362D;
            }
        </style>
        <table class="table table-striped table-bordered table-hover text-center ">
            <thead id="thead">
                <tr class="alert-success text-center text-dark">

                    <th width="50px">Codigo</th>
                    <th width="200px">Nivel</th>
                    <th width="300px">Descripcion</th>
                </tr>
            </thead>
            @foreach (var NivelUsuarios in Model.NivelUsuarios)
            {
                <tr>
                    <td>@NivelUsuarios.CodigoNivel</td>
                    <td>@NivelUsuarios.NombreNivel</td>
                    <td>@NivelUsuarios.DescripcionNivel</td>
                </tr>

            }
        </table>
    </div>
</div>
<<br /><br /><br /><br />

src/Actividad/Views/Shared/DesplegarUsuarios.cshtml
<div class="container ">
    <div class="table-responsive">
        <style>
            #thead {
                border-bottom: solid 5px #0F362D;
            }
        </style>

        <table class="table table-striped table-bordered table-hover text-center border-info ">
            
            <thead id="thead">
                <tr class="alert-success text-center text-dark">
                    <th>Codigo</th>
                    <th>Nombre y apellidos</th>
                    <th>Cuenta</th>
                    <th colspan="2">Nivel</th>
                </tr>
            </thead>
      @foreach (var usuarios in Model.Usuarios)
            {
                
                <tr class="border-info">

                    <td>@usuarios.CodigoUsuario</td>
                    <td>@usuarios.NombreUsuario @usuarios.ApellidoUsuario </td>
                    <td>@usuarios.CuentaUsuario</td>
                    <td>@usuarios.NivelUsuarios.NombreNivel</td>
                    <td><a  class="btn btn-success btn-sm" asp-controller="Solicitados" asp-action="AgregarASolicitados"
                           asp-route-codigoUsuario="@usuarios.CodigoUsuario">Solicitar</a></td>
                 
                </tr>
            }

        </table>
    </div>
</div> <br />

src/Actividad/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport"  content="width=device-width, initial-scale=1"/>
    <link href="~/lib/font-awesome/web-fonts-with-css/css/fontawesome-all.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Tema/2-col-portfolio.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="~/lib/jquery/dist/jquery.js" ></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
   
 </head>
    <body>
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand" href="../Home/Index">Sistema</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="../Home/Index" >
                                Inicio 
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>&nbsp;&nbsp;
                        @await Component.InvokeAsync("NivelesMenu")
                        &nbsp;&nbsp;
                        @await Component.InvokeAsync("SolicitadosContenido")
                    </ul>
                </div>
            </div>
        </nav><div class="container">
        @RenderBody()</div>
        <br />
        <br />
        <br />
        <br />
            <div class="container">
            <!-- /.row -->
            <!-- Pagination -->
            <ul class="pagination justify-content-center">
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">1</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">2</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#">3</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
            </ul>
        </div>
        <br />
        <br />
        <br />
        <br />
        <!-- /.container -->
        <!-- Footer -->
        <footer class="py-5 bg-dark">
            <div class="container">
                <p class="m-0 text-center text-white">Copyright &copy; Programacion 3/2018</p>
            </div>
            <!-- /.container -->
        </footer>
        <!-- Bootstrap core JavaScript -->
       
    </body>
</html>